added stairs exam 2018-01-17 with FRR
KatharaFramework/Kathara-Labs pull request #15
Opened 2022-12-19 21:56 UTC by Francesco9932

2022-12-22 17:15 UTC, lorenzo93 requested changes
Hi @Francesco9932 

thanks very much for your work, we appreciate it a lot.
I've made some comments on your code. Notice that, some of them are just on one file but they should be seen as "global" comments.

2022-12-22 17:15 UTC, lorenzo93 commented on Exam Labs/2018-01-17 Stairs/lab/as1r1/etc/frr/frr.conf
> +no bgp network import-check
Not needed, the announced prefixes are the same as the interfaces prefixes

2022-12-22 17:15 UTC, lorenzo93 commented on Exam Labs/2018-01-17 Stairs/lab/as1r2/etc/frr/frr.conf
> +set metric 10
Please, add indentation to improve readability. (you can find the correct indentation running the command show running-config inside vtysh)

2022-12-22 17:15 UTC, lorenzo93 commented on Exam Labs/2018-01-17 Stairs/lab/lab.conf
> +as1r1[0]="A"
Please, add at the start of the lab.conf the metadata (you can see an example other labs) and feel free to put your name as author :)

2022-12-22 21:39 UTC, Francesco9932 commented
Hi @lorenzo93 

Thanks for your appreciation of my and George work in making this lab. 
I fixed everything you suggested me and i pushed the changes.

2023-01-09 14:04 UTC, lorenzo93 commented
Hi @Francesco9932 ,

I've checked your lab and everything works fine.
Just two small changes and I'll merge your PR.

1. Remember to update the `lab.zip` file with the new changes
2. Please, to improve readability, add indentation to the `frr.conf`files. (You can find the correct indentation running the command `show running-config` inside `vtysh`)

2023-01-10 20:29 UTC, Francesco9932 commented
Hi @lorenzo93 i've added the correct indentation in frr.conf and i've updated the lab.zip version of the lab with the new changes that you suggested me.

2023-01-11 11:38 UTC, lorenzo93 approved these changes

2023-01-11 11:39 UTC, merged