Add basic-ipv4 scenario
KatharaFramework/Kathara-Labs pull request #40
Opened 2023-11-21 12:02 UTC by tcaiazzi

This PR adds the new `basic-ipv4` scenario to the main-labs.

The scenario shows basic IPv4 configuration commands, the usage of ping and traceroute, and the related ARP behavior.

The lab uses the [Wireshark](https://github.com/KatharaFramework/Kathara-Labs/tree/main/tutorials/capture-packets) device to provide a more interactive and immersive experience.

2023-11-21 15:41 UTC, Skazza94 approved these changes

2023-11-22 15:17 UTC, lorenzo93 requested changes
Everything looks good, there is just a small change :)

2023-11-22 15:40 UTC, lorenzo93 commented on main-labs/basic-topics/basic-ipv4/0130-kathara-lab_basic-ipv4.pptx
On slide 34, there is an "f" missing from the title (sniff, not snif)

2023-11-23 12:44 UTC, tcaiazzi commented
@lorenzo93 I made the changes!

2023-11-29 17:54 UTC, lorenzo93 approved these changes

2023-11-29 17:54 UTC, merged