Add SDN-Openflow Labs
KatharaFramework/Kathara-Labs pull request #41
Opened 2023-12-01 16:40 UTC by RicGobs

#### Topic
Add 6 newtork scenarios

#### The network scenarios added
- main-labs/sdn-openflow/01-POX_Controller
- main-labs/sdn-openflow/02-POX_Core_Object
- main-labs/sdn-openflow/03-POX_Events
- main-labs/sdn-openflow/04-POX_Work_with_Packets
- main-labs/sdn-openflow/05-POX_Datapaths
- main-labs/sdn-openflow/06-POX_Discovery

#### The network scenarios description
Descriptions are written in the README, for each scenario

#### The steps to test the network scenarios
All steps are written in the README, for each scenario

2023-12-15 10:31 UTC, tcaiazzi commented
Hi @RicGobs, 

First of all thanks for finding time to contribute to Kathará. We really appreciate it. 
 
The PR seems excellent! However, to include it in the main-labs we need several changes: 
1. We need a POX Docker Image, to avoid importing POX as Git submodule.  The new image should be based on the `kathara/base` image.
2. Change the labs to use the new Docker image.
3. All the names of the labs must be lowercase and `-` is preferred to `_`.
4. Add a `pox` directory inside the sdn-openflow one and put all the scenarios in it. 

If you think this is too much work, you can simply change the PR to add the scenarios in the [community-labs](https://github.com/KatharaFramework/Kathara-Labs/tree/main/community-labs).  

Let me know what you prefer. 

Do not hesistate to write me, if you need any help. 

Many thanks for the support, 
Tommaso

2024-01-22 17:17 UTC, tcaiazzi commented
Hi @RicGobs, 

I started the refactor of the PR so that you can continue it when (and only if) you have time and will :)

I re-organized the directories and finished refactoring the `01-pox-controller` scenario.
Furthermore, I used the attached Dockerfile ([Dockerfile.zip](https://github.com/KatharaFramework/Kathara-Labs/files/14013305/Dockerfile.zip)) to build the `kathara/pox` image, which also contains `Python3.9` to improve compatibility with POX. 

To build the image, decompress the `.zip` archive in a directory of your choice. Then, open a terminal in that directory and type:
```bash
docker build -t kathara/pox .
```
This will build the image `kathara/pox` locally on your machine using the Dockerfile in the current directory (represented by the `.` at the end of the command). 

Once we finished the refactor, I will push the image to the Docker Hub.

Please let me know if you need any help or further explanation. 

Many thanks for the help, 
Tommaso

2024-01-22 18:16 UTC, RicGobs commented
Hi @tcaiazzi,

I have seen the refactored 01-pox-controller scenario. 

Taking a quick look I think I have understood the various changes I need to make in the various scenarios.
I haven't built the docker image yet (thanks for it), I will do it in future together with the modification of the various scenarios.

If I encounter problems during editing, I'll write to you. 
See you soon, Bye.

Riccardo

2024-02-10 13:26 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/01-pox-controller/README.md
> +python3 /pox/pox.py forwarding.l2_learning openflow.of_01 -port=6653
Maybe is better to leave here `python3.9`, since it is the version supported by POX

2024-02-10 13:33 UTC, tcaiazzi requested changes
Thanks, @RicGobs ❤️

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/01-pox-controller/README.md
> +Launch in the root@controller:
I prefer the old version, since you should already have the controller terminal opened from the `kathara lstart` command.

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/01-pox-controller/README.md
> +python3 /pox/pox.py forwarding.l2_learning openflow.of_01 -port=6653
Maybe is better to leave here `python3.9`, since it is the version supported by POX

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/02-pox-core-object/README.md
> +Launch ```python3 /pox/pox.py A B openflow.of_01 -port=6653``` in the root@controller
`python3.9`

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/03-pox-events/README.md
> +Launch ```python3 /pox/pox.py A_listener B_listener openflow.of_01 -port=6653``` in the root@controller
`python3.9`

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/03-pox-events/command.txt
> +python3 /pox/pox.py A_listener B_listener openflow.of_01 -port=6653
`python3.9`

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/04-pox-work-with-packets/README.md
> +Launch ```python3 /pox/pox.py Packet_check openflow.of_01 -port=6653``` in the root@controller
`python3.9`

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/05-pox-datapaths/README.md
> +Launch ```python3 /pox/pox.py reflector openflow.of_01 -port=6653``` in the root@controller
`python3.9`

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/05-pox-datapaths/command.txt
> +python3 /pox/pox.py reflector openflow.of_01 -port=6653
`python3.9`

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/06-pox-discovery/README.md
> +Launch ```python3 /pox/pox.py link_discovery_solution1 openflow.of_01 -port=6653``` in the root@controller
`python3.9`

2024-02-10 13:33 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/07-host_discovery/command.txt
> +python3 /pox/pox.py openflow.of_01 -port=6653 host_discovery link_discovery
`python3.9`

2024-02-10 16:36 UTC, RicGobs commented
Hi @tcaiazzi ,

Ok. I will do these changes.
I have to check the last lab (pox-routing) and then I will upload all.

If there are other things that you need/want to add, tell me.

2024-02-11 06:06 UTC, RicGobs commented
Hi @tcaiazzi,

I have changed all python3 in python3.9, apart from the 09-Routing lab which uses networkx: the same command launched with 'python3' works while  it doesn't work with 'python3.9'.

I think that the problem is that I am installing the networkx library with APT. The networkx version is 2.8.8, that is not the last one. PIP installation does not complete the build.

Here it is the modified image.
[Dockerfile.zip](https://github.com/KatharaFramework/Kathara-Labs/files/14231420/Dockerfile.zip)

About the `kathara connect controller` command, if this was the question, I have advised to use this command in the readme to allow people to paste the follow (long) pox command in the terminal. 
I remember that it is not possible to make paste in Kathara xterms.

If needed, I change the readme.

2024-02-12 10:49 UTC, tcaiazzi commented
Hi @RicGobs, 

Thanks for the changes! 

Here an updated Dockerfile ([Dockerfile.zip](https://github.com/KatharaFramework/Kathara-Labs/files/14237411/Dockerfile.zip)), please let me know if it works :) 

> About the kathara connect controller command, if this was the question, I have advised to use this command in the readme to allow people to paste the follow (long) pox command in the terminal.
> I remember that it is not possible to make paste in Kathara xterms.
Actually, it is possible to make copy/paste on `xterm`.  To copy something, you have to highlight it with the cursor, then for pasting, you can press the mouse wheel :innocent: 

Moreover, consider that it is possible to change the terminal emulator from the settings, so not all the users leverage on `xterm`.  

Thanks for all!

2024-02-13 18:12 UTC, RicGobs commented
Hi @tcaiazzi,

Here the changes:
- `kathara connect controller` logic removed in all readme.
- Your pox image solved the problem. Now all readme have `python3.9`.
- Deleted command.txt files that were redundant.
- Standardized the readme of the various labs.

Checked all labs, they are correct (to my knowledge).

Bye ❤️

2024-02-14 10:20 UTC, tcaiazzi approved these changes

2024-02-14 10:37 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/05-pox-datapaths/h1/home/send_receive.py
We need to change the method names from Italian to English

2024-02-14 10:46 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/07-pox-host-discovery/controller/pox/ext/host_discovery.py
> +class hostDiscovery:
First letter of classes should be uppercase

2024-02-14 11:02 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/07-pox-host-discovery/controller/pox/ext/host_discovery.py
> +class hostDiscovery:
However, I noticed that POX uses this convention. So maybe is better to leave as you did.

2024-02-14 11:04 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/05-pox-datapaths/h1/home/send_receive.py
Change methods name to English

2024-02-14 11:06 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/09-pox-routing/controller/pox/ext/max_throughput_routing.py
> +class Max_throughput_routing:
Ugly name.  `MaxThroughputRouting` is better.

2024-02-14 11:11 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/images/images.drawio
Is this file useful? Although we can remove it.

2024-02-14 11:16 UTC, tcaiazzi approved these changes
Hi @RicGobs, 

The PR seems completed. I only made some minor changes to some README and other files. 

Super thanks for all your effort and your contribution! ❤️ 🚀

2024-02-14 11:17 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/05-pox-datapaths/h1/home/send_receive.py
Done

2024-02-14 11:18 UTC, tcaiazzi commented on main-labs/sdn-openflow/pox/09-pox-routing/controller/pox/ext/max_throughput_routing.py
> +class Max_throughput_routing:
Ops forgot to change before approving the PR.

2024-02-26 22:53 UTC, RicGobs commented
Thanks @lorenzo93 😇

2024-03-11 09:25 UTC, tcaiazzi approved these changes

2024-03-11 09:28 UTC, merged